AppGateWay_Operation_FrontEnd/Controllers/GatewayController.cs
using AppGateWay_Operation_FrontEnd.API_Operation;
using AppGateWay_Operation_FrontEnd.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using System;
using System.Collections.Generic;
using System.Net;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc.ViewFeatures;
using Newtonsoft.Json;

namespace AppGateWay_Operation_FrontEnd.Controllers
{
    public class GatewayController : Controller
    {
        private readonly string _apiHostedUrl = string.Empty;
        private readonly IOptions<ApiOperations.CustomSettings> _settings;
        private List<Resultcs> _resultset;


        public GatewayController(IOptions<ApiOperations.CustomSettings> settings)
        {
            _settings = settings;
            _apiHostedUrl = _settings.Value.azureLogUrl;
            _resultset = new List<Resultcs>();
        }

        public IActionResult Index()
        {
            return View();
        }


        public ActionResult AddProbe(GatewayViewModel inputData)
        {
            inputData.operation = Operations.CreateProbe.ToString();
            var result = ApiOperations.ExecutivePutApi(_apiHostedUrl, inputData);

            if (result == HttpStatusCode.OK)
            {
                _resultset.Add(new Resultcs() { Message = "Probe created successfully", Status = "Completed", State = true });
                AddAddHttpSettings(inputData);
            }
            else
            {
                _resultset.Add(new Resultcs() { Message = "Failed to create Probe", Status = "Error", State = false });
                _resultset.Add(new Resultcs() { Message = "Unable to create HttpSettings", Status = "Not Performed", State = false });
                _resultset.Add(new Resultcs() { Message = "Unable to create BackendAddressPool", Status = "Not Performed", State = false });
                _resultset.Add(new Resultcs() { Message = "Unable to create Rule", Status = "Not Performed", State = false });
            }

            TempData.Put("Result", _resultset);

            return RedirectToAction("SendResult");

        }

        public ActionResult SendResult()
        {
            var _resultset = TempData.Get<List<Resultcs>>("Result");
            return View(_resultset);
        }

        [HttpGet]
        public HttpStatusCode AddAddHttpSettings(GatewayViewModel inputData)
        {
            //var inputData = (GatewayViewModel)TempData["ipData"];

            if (TempData["myData"] != null)
                _resultset = TempData["myData"] as List<Resultcs>;

            TempData.Keep();

            inputData.operation = Operations.AddHTTPSettings.ToString();
            var result = ApiOperations.ExecutivePutApi(_apiHostedUrl, inputData);


            if (result == HttpStatusCode.OK)
            {
                _resultset.Add(new Resultcs() { Message = "HttpSettings created successfully", Status = "Completed", State = true });
                //RedirectToAction("AddBackendAddressPool", "Gateway");
                return AddBackendAddressPool(inputData);

            }
            else
            {
                _resultset.Add(new Resultcs() { Message = "Failed to create HttpSettings", Status = "Error", State = false });
                _resultset.Add(new Resultcs() { Message = "Unable to create BackendAddressPool", Status = "Not Performed", State = false });
                _resultset.Add(new Resultcs() { Message = "Unable to create Rule", Status = "Not Performed", State = false });
            }
            return HttpStatusCode.BadRequest;
        }

        [HttpGet]
        public HttpStatusCode AddBackendAddressPool(GatewayViewModel inputData)
        {
            //var inputData = (GatewayViewModel)TempData["ipData"];
            inputData.operation = Operations.BackendAddressPool.ToString();

            var result = ApiOperations.ExecutivePutApi(_apiHostedUrl, inputData);

            if (result == HttpStatusCode.OK)
            {
                _resultset.Add(new Resultcs() { Message = "BackendAddressPool created successfully", Status = "Completed", State = true });
                return AddRule(inputData);
            }
            else
            {
                _resultset.Add(new Resultcs() { Message = "Unable to create BackendAddressPool", Status = "Error", State = false });
                _resultset.Add(new Resultcs() { Message = "Unable to create Rule", Status = "Not Performed", State = false });
            }

            return HttpStatusCode.BadRequest;

        }

        [HttpGet]
        public HttpStatusCode AddRule(GatewayViewModel inputData)
        {
            //GatewayViewModel inputData = (GatewayViewModel)TempData["ipData"];
            inputData.operation = Operations.AddRule.ToString();

            var result = ApiOperations.ExecutivePutApi(_apiHostedUrl, inputData);

            if (result == HttpStatusCode.OK)
            {
                _resultset.Add(new Resultcs() { Message = "Rule created successfully", Status = "Completed", State = true });
                return HttpStatusCode.OK;
            }
            else
            {
                _resultset.Add(new Resultcs() { Message = "Unable to create Rule", Status = "Error", State = false });
            }

            return HttpStatusCode.BadRequest;
        }



    }


    public static class TempDataExtensions
    {
        public static void Put<T>(this ITempDataDictionary tempData, string key, T value) where T : class
        {
            tempData[key] = JsonConvert.SerializeObject(value);
        }

        public static T Get<T>(this ITempDataDictionary tempData, string key) where T : class
        {
            object o;
            tempData.TryGetValue(key, out o);
            return o == null ? null : JsonConvert.DeserializeObject<T>((string)o);
        }
    }

    //public static class SessionExtensions
    //{
    //    public static void Set<T>(this ISession session, string key, T value)
    //    {
    //        session.SetString(key, JsonConvert.SerializeObject(value));
    //    }

    //    public static T Get<T>(this ISession session, string key)
    //    {
    //        var value = session.GetString(key);
    //        return value == null ? default(T) :
    //            JsonConvert.DeserializeObject<T>(value);
    //    }
    //}
}

AppGateWay_Operation_FrontEnd/Views/Gateway/Index.cshtml
@model AppGateWay_Operation_FrontEnd.Models.GatewayViewModel

@{
    ViewData["Title"] = "Index";
}

<h2>Configure Application Gateway to Cloud</h2>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="AddProbe">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="operation" class="control-label"></label>
                <input asp-for="operation" class="form-control" />
                <span asp-validation-for="operation" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SubscriptionId" class="control-label"></label>
                <input asp-for="SubscriptionId" class="form-control" />
                <span asp-validation-for="SubscriptionId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ResourceGroupName" class="control-label"></label>
                <input asp-for="ResourceGroupName" class="form-control" />
                <span asp-validation-for="ResourceGroupName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ApplicationGatewayName" class="control-label"></label>
                <input asp-for="ApplicationGatewayName" class="form-control" />
                <span asp-validation-for="ApplicationGatewayName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProbeName" class="control-label"></label>
                <input asp-for="ProbeName" class="form-control" />
                <span asp-validation-for="ProbeName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Protocol" class="control-label"></label>
                <input asp-for="Protocol" class="form-control" />
                <span asp-validation-for="Protocol" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Host" class="control-label"></label>
                <input asp-for="Host" class="form-control" />
                <span asp-validation-for="Host" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Probepath" class="control-label"></label>
                <input asp-for="Probepath" class="form-control" />
                <span asp-validation-for="Probepath" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="HttpSettingsName" class="control-label"></label>
                <input asp-for="HttpSettingsName" class="form-control" />
                <span asp-validation-for="HttpSettingsName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="HttpSettingsPort" class="control-label"></label>
                <input asp-for="HttpSettingsPort" class="form-control" />
                <span asp-validation-for="HttpSettingsPort" class="text-danger"></span>
            </div>
            @*<div class="form-group">
                    <label asp-for="HttpSettingsProtocol" class="control-label"></label>
                    <input asp-for="HttpSettingsProtocol" class="form-control" />
                    <span asp-validation-for="HttpSettingsProtocol" class="text-danger"></span>
                </div>*@
            <div class="form-group">
                <label asp-for="BckendPoolName" class="control-label"></label>
                <input asp-for="BckendPoolName" class="form-control" />
                <span asp-validation-for="BckendPoolName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BckendipAddress" class="control-label"></label>
                <input asp-for="BckendipAddress" class="form-control" />
                <span asp-validation-for="BckendipAddress" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RuleName" class="control-label"></label>
                <input asp-for="RuleName" class="form-control" />
                <span asp-validation-for="RuleName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RulePath" class="control-label"></label>
                <input asp-for="RulePath" class="form-control" />
                <span asp-validation-for="RulePath" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="brearerToken" class="control-label"></label>
                <input asp-for="brearerToken" class="form-control" />
                <span asp-validation-for="brearerToken" class="text-danger"></span>
            </div>
            <div class="form-group">
                <button type="submit" value="Create" onclick="location.href='@Url.Action("AddProbe", "Gateway")'">
                    Create
                </button>

            </div>
        </form>
    </div>
</div>

AppGateWay_Operation_FrontEnd/Views/Gateway/SendResult.cshtml
@model IEnumerable<AppGateWay_Operation_FrontEnd.Models.Resultcs>

@{
    ViewData["Title"] = "Configuration Result";
}

<h2>Final Configuration Result </h2>

<table class="table">
    <thead>
        <tr>
            <th>
                @* @Html.DisplayNameFor(model => model.Message)*@
                <label>Action Performed</label>
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Status)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.State)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Message)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Status)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.State)
                </td>

            </tr>
        }
    </tbody>
</table>